services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: devcollab
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./back-end
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://devuser:devpass@db:5432/devcollab
    ports:
      - "3000:3000"
    command: npm run start:prod

  frontend:
    build:
      context: ./front-end
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  postgres_data:
