services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: devcollab
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./back-end
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://devuser:devpass@db:3306/devcollab
    ports:
      - "3000:3000"
    command: npm run start:prod

  frontend:
    build:
      context: ./front-end
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  mysql_data:
