apiVersion: apps/v1
kind: Deployment
metadata:
  name: devcollab-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devcollab-backend
  template:
    metadata:
      labels:
        app: devcollab-backend
    spec:
      containers:
        - name: backend
          image: devcollab-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: devcollab-backend
spec:
  selector:
    app: devcollab-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
