apiVersion: apps/v1
kind: Deployment
metadata:
  name: devcollab-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devcollab-frontend
  template:
    metadata:
      labels:
        app: devcollab-frontend
    spec:
      containers:
        - name: frontend
          image: devcollab-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devcollab-frontend
spec:
  selector:
    app: devcollab-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
